apiVersion: v1
kind: Service
metadata:
  name: zeppelin-k8s-service
  labels:
    app: zeppelin-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: zeppelin-server
  type: NodePort